# Generated by Django 2.0.4 on 2018-04-25 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiModel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('typefield', models.CharField(choices=[(int, 'integer'), (float, 'float'), (str, 'string')], default='string', max_length=9)),
                ('required', models.BooleanField()),
                ('range_start', models.IntegerField()),
                ('range_end', models.IntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('api', models.ManyToManyField(to='app.ApiModel', verbose_name='list of apis')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='apimodel',
            name='field',
            field=models.ManyToManyField(to='app.FieldModel', verbose_name='list of fields'),
        ),
    ]
