# Generated by Django 2.0.4 on 2018-04-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmodel',
            name='range_end',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='range_start',
            field=models.IntegerField(editable=False),
        ),
    ]
