# Generated by Django 2.0.4 on 2018-04-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180425_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmodel',
            name='typefield',
            field=models.CharField(choices=[('int', 'integer'), ('float', 'float'), ('str', 'string')], default='string', max_length=9),
        ),
    ]
