# Generated by Django 2.0.4 on 2018-04-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180425_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjModel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('field', models.ManyToManyField(to='app.FieldModel', verbose_name='list of fields')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='apimodel',
            name='obj',
            field=models.ManyToManyField(to='app.ObjModel', verbose_name='list of objects'),
        ),
    ]
