# Generated by Django 2.0.4 on 2018-04-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_apimodel_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodel',
            name='obj',
            field=models.ManyToManyField(to='app.ObjModel', verbose_name='list of objs'),
        ),
    ]
