# Generated by Django 2.0.4 on 2018-04-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_apimodel_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apimodel',
            old_name='field',
            new_name='fields',
        ),
        migrations.RenameField(
            model_name='objmodel',
            old_name='field',
            new_name='fields',
        ),
        migrations.RemoveField(
            model_name='apimodel',
            name='obj',
        ),
        migrations.AddField(
            model_name='apimodel',
            name='objects',
            field=models.ManyToManyField(to='app.ObjModel', verbose_name='list of objects'),
        ),
    ]
