# Generated by Django 2.0.4 on 2018-04-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180427_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apimodel',
            old_name='fields',
            new_name='fieldElements',
        ),
        migrations.RenameField(
            model_name='objmodel',
            old_name='fields',
            new_name='fieldElements',
        ),
    ]
