# Generated by Django 2.0.4 on 2018-04-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180427_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apimodel',
            old_name='fieldElements',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='objmodel',
            old_name='fieldElements',
            new_name='field',
        ),
        migrations.RemoveField(
            model_name='apimodel',
            name='objects',
        ),
        migrations.AddField(
            model_name='apimodel',
            name='obj',
            field=models.ManyToManyField(to='app.ObjModel', verbose_name='list of objs'),
        ),
    ]
